/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IncompleteJobReq.java
 *
 * Created on 06 18, 13, 8:27:24 AM
 */
package GUI;

import Models.JobReqAssignment;
import Service_impl.JRF_serv_impl;
import Service_interface.JRF_serv_interface;
import Tool.ErrorException;
import Tool.Methods;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hatiefm
 */
public class IncompleteJobReq extends javax.swing.JDialog {

    /** Creates new form IncompleteJobReq */
    private JTextField t1;
    private JTextField t2;
    private JTextField t3;
    private JComboBox c1;
    private JLabel l1;
    private JLabel l2;
    private JButton b1;
    private JButton b2;
    
    private Methods m = new Methods();
    private JRF_serv_interface jrfServ;
    
    private ArrayList<JobReqAssignment> list = new ArrayList<JobReqAssignment>();
    
    public IncompleteJobReq(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("List of Job Requests not yet completed by IT Staff");
        
        jrfServ = new JRF_serv_impl();
        
        try{
            list = jrfServ.getAssignment_status(-1);//incomplete Job Req
        }catch(ErrorException ex){ex.printMessage();}
        m.displayJobReqAssignmentList((DefaultTableModel)jTable1.getModel(), list);
    }
    
    public void setFields(JTextField t1, JTextField t2, JTextField t3, JComboBox c1,
            JLabel l1, JLabel l2, JButton b1, JButton b2){
        this.t1 = t1;
        this.t2 = t2;
        this.t3 = t3;
        this.c1 = c1;
        this.l1 = l1;
        this.l2 = l2;
        this.b1 = b1;
        this.b2 = b2;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Control No.", "Date Assigned", "Assigned to", "Status", "Assigned by"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setShowHorizontalLines(false);
        jTable1.setShowVerticalLines(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(1).setResizable(false);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(2).setResizable(false);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(250);
        jTable1.getColumnModel().getColumn(3).setResizable(false);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(4).setResizable(false);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(250);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        if(index >= 0){
            JobReqAssignment j = list.get(index);
            t1.setText((j.getDate_assigned().getMonth()+1)+"/"+j.getDate_assigned().getDate()
                    +"/"+(j.getDate_assigned().getYear()+1900));
            t2.setText(j.getControl_no());
            c1.setSelectedItem(j.getAssigned_to().getEmp_id()+" "+j.getAssigned_to().getCompleteName());
            l1.setText(j.getAssigned_to().getEmp_position());
            t3.setText(j.getAssigned_by().getCompleteName());
            l2.setText(j.getAssigned_by().getEmp_position());
            
            b1.setEnabled(true);
            b2.setEnabled(true);
            this.dispose();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                IncompleteJobReq dialog = new IncompleteJobReq(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
