/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SearhJRF.java
 *
 * Created on 06 13, 13, 8:15:41 AM
 */
package GUI;

import Models.Department;
import Models.JRF;
import Models.Person;
import Service_impl.Department_serv_impl;
import Service_impl.JRF_serv_impl;
import Service_impl.Person_serv_impl;
import Service_interface.Department_serv_interface;
import Service_interface.JRF_serv_interface;
import Service_interface.Person_serv_interface;
import Tool.ErrorException;
import Tool.Methods;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hatiefm
 */
public class SearchJRF extends javax.swing.JDialog {

    /** Creates new form SearhJRF */
    private JTextField t1;
    private JTextField t2;
    private JTextField t3;
    private JComboBox c1;
    private JTextField t4;
    private JTextField t5;
    private JTextField t6;
    private JTextField t7;
    private JCheckBox check1;
    private JCheckBox check2;
    private JCheckBox check3;
    private JTextArea a1;
    private JTextArea a2;
    private JTextField t8;
    private JTextField t9;
    private JTextField t10;
    private JLabel l1;
    
    private JTextField t11;
    private JTextArea a3;
    private JButton b4;
    
    private JTextField t12;
    
    private JButton b1;
    private JButton b2;
    private JButton b3;
    
    private int iden;
    private int index;
    private Methods m = new Methods();
    private ArrayList<JRF> jrfList = new ArrayList<JRF>();
    
    private Department_serv_interface dServ;
    private Person_serv_interface pServ;
    private JRF_serv_interface jrfServ;
    
    public SearchJRF(javax.swing.JDialog parent, boolean modal, int iden) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Search Job Requests");
        this.iden = iden;
        
        dServ = new Department_serv_impl();
        pServ = new Person_serv_impl();
        jrfServ = new JRF_serv_impl();
        
        setEnable(false);
        jButton2.setEnabled(false);
        m.loadDepartment(jComboBox1);
    }
    
    public SearchJRF(javax.swing.JFrame parent, boolean modal, int iden) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Search Job Requests");
        this.iden = iden;
        
        dServ = new Department_serv_impl();
        pServ = new Person_serv_impl();
        jrfServ = new JRF_serv_impl();
        
        setEnable(false);
        jButton2.setEnabled(false);
        m.loadDepartment(jComboBox1);
    }
    
    private void setEnable(Boolean bool){
        jComboBox1.setEnabled(bool);
        jTextField1.setEnabled(bool);
        jComboBox2.setEnabled(bool);
    }
    
    public void setFields(JTextField t1,JTextField t2,JTextField t3,JComboBox c1,
            JTextField t4,JTextField t5,JTextField t6,JTextField t7,
            JCheckBox check1,JCheckBox check2,JCheckBox check3,JTextArea a1,
            JTextArea a2,JTextField t8,JTextField t9,JTextField t10,JLabel l1){
        this.t1 = t1;
        this.t2 =  t2;
        this.t3 = t3;
        this.c1 = c1;
        this.t4 = t4;
        this.t5 = t5;
        this.t6 = t6;
        this.t7 = t7;
        this.check1 = check1;
        this.check2 = check2;
        this.check3 = check3;
        this.a1 = a1;
        this.a2 = a2;
        this.t8 = t8;
        this.t9 = t9;
        this.t10 = t10;
        this.l1 = l1;
    }
    
    public void setButtons(JButton b1,JButton b2,JButton b3){
        this.b1 = b1;
        this.b2 = b2;
        this.b3 = b3;
    }
    
    public void setTextField(JTextField t11, JTextArea a3, JButton b4){
        this.t11 = t11;
        this.a3 = a3;
        this.b4 = b4;
    }
    
    public void setTextFIeld1(JTextField t12){
        this.t12 = t12;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Search Job Request");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jRadioButton1.setText("Office");
        jRadioButton1.setFocusable(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jRadioButton2.setText("Employee ID");
        jRadioButton2.setFocusable(false);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jRadioButton3.setText("Job Request On");
        jRadioButton3.setFocusable(false);
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jRadioButton4.setText("Date");
        jRadioButton4.setFocusable(false);
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jLabel2.setText("Office:");

        jComboBox1.setFocusable(false);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jLabel3.setText("Employee ID:");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jLabel4.setText("Request On:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hardware/OS", "Network", "Database" }));
        jComboBox2.setFocusable(false);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jLabel5.setText("Date:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Control No.", "Date Created", "Office", "Employee", "Request On"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setShowHorizontalLines(false);
        jTable1.setShowVerticalLines(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(1).setResizable(false);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(2).setResizable(false);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(3).setResizable(false);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(250);
        jTable1.getColumnModel().getColumn(4).setResizable(false);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(150);

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Job Request Description");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextArea1);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/find.png"))); // NOI18N
        jButton1.setToolTipText("Find");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/application_get.png"))); // NOI18N
        jButton2.setToolTipText("Select");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/application_delete.png"))); // NOI18N
        jButton3.setToolTipText("Cancel");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(!jRadioButton1.isSelected() && !jRadioButton2.isSelected() && 
                !jRadioButton3.isSelected() && !jRadioButton4.isSelected()){
            JOptionPane.showMessageDialog(this, "Error! Please select search option.", 
                    "Error Message", JOptionPane.ERROR_MESSAGE);
        }else{
            try{
                if(jRadioButton1.isSelected()){
                    String dept_code = jComboBox1.getSelectedItem().toString();
                    if(dept_code.equalsIgnoreCase("Select Office")){
                        JOptionPane.showMessageDialog(this, "Error! Please select office properly.", 
                                "Error Message", JOptionPane.ERROR_MESSAGE);
                    }else{
                        Department d = dServ.getDepartmentbyCode(dept_code);
                        
                        jrfList = jrfServ.getJRF_Office(d.getDept_id());
                    }
                }else if(jRadioButton2.isSelected()){
                    String emp_id = jTextField1.getText();
                    if(emp_id.isEmpty()){
                        JOptionPane.showMessageDialog(this, "Error! Employee ID required.", 
                                "Error Message", JOptionPane.ERROR_MESSAGE);
                    }else{
                        Person p = pServ.getPersonID(emp_id);
                        if(p == null){
                            JOptionPane.showMessageDialog(this, "Error! Employee ID: "+emp_id+" doesn't exist.", 
                                    "Error Message", JOptionPane.ERROR_MESSAGE);
                        }else{
                            jrfList = jrfServ.getJRF_employee(emp_id);
                        }
                    }
                }else if(jRadioButton3.isSelected()){
                    String req_on_str = jComboBox2.getSelectedItem().toString();
                    int req_on;
                    if(req_on_str.equalsIgnoreCase("Hardware/OS"))
                        req_on = 0;
                    else if(req_on_str.equalsIgnoreCase("Network"))
                        req_on = 1;
                    else req_on = 2;
                    
                    jrfList = jrfServ.getJRF_Job_req_on(req_on);
                }else if(jRadioButton4.isSelected()){
//                    Date date = jDateChooser1.getDate();
//                    if(date == null){
//                        JOptionPane.showMessageDialog(this, "Error! Date required.", 
//                                "Error Message", JOptionPane.ERROR_MESSAGE);
//                    }else{
//                        String date_str = (date.getYear()+1900)+"-"+(date.getMonth()+1)+"-"+
//                                date.getDate();
//                        jrfList = jrfServ.getJRF_date(date_str);
//                    }
                }
                //display data table
                m.displayJRF((DefaultTableModel)jTable1.getModel(), jrfList);
            }catch(ErrorException ex){ex.printMessage();}
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        setEnable(false);
        jComboBox1.setEnabled(true);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        setEnable(false);
        jTextField1.setEnabled(true);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        setEnable(false);
        jComboBox2.setEnabled(true);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        setEnable(false);
//        jDateChooser1.setEnabled(true);
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        index = jTable1.getSelectedRow();
        if(index >= 0){
            jButton2.setEnabled(true);
            jTextArea1.setText(jrfList.get(index).getJob_description());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JRF jrf = jrfList.get(index);
        if(iden == 1){//get info
            t1.setText((jrf.getDate_app().getMonth()+1)+"/"+jrf.getDate_app().getDate()+
                    "/"+(jrf.getDate_app().getYear()+1900));
            t2.setText(jrf.getEmail());
            t3.setText(jrf.getContact());
            c1.setSelectedItem(jrf.getDept().getDept_code());
            t4.setText(jrf.getRoom());
            t5.setText(jrf.getRequested_by().getEmp_id());
            t6.setText(jrf.getRequested_by().getCompleteName());
            t7.setText(jrf.getRequested_by().getEmp_position());
            
            if(jrf.getJob_req_on() == 0)
                check1.setSelected(true);
            else if(jrf.getJob_req_on() == 1)
                check2.setSelected(true);
            else check3.setSelected(true);
            
            a1.setText(jrf.getJob_description());
            a2.setText(jrf.getAction_taken());
            t8.setText(jrf.getApproved_by().getEmp_id());
            t9.setText(jrf.getApproved_by().getCompleteName());
            t10.setText(jrf.getApproved_by().getEmp_position());
            l1.setText(jrf.getControl_no());
            
            b1.setEnabled(true);
            b2.setEnabled(true);
            b3.setEnabled(true);
        }else if(iden == 2){
            t11.setText(jrf.getControl_no());
            a3.setText(jrf.getAction_taken());
            
            t11.setEnabled(false);
            a3.setEnabled(false);
            b4.setEnabled(true);
        }else if(iden == 3){
            t12.setText(jrf.getControl_no());
        }
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                SearhJRF dialog = new SearhJRF(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
